# Generated by Django 3.1.1 on 2020-09-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knjiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=32)),
                ('autor', models.CharField(max_length=32)),
                ('izdavac', models.CharField(max_length=16)),
                ('godina_izdanja', models.IntegerField()),
                ('zanr', models.CharField(max_length=32)),
                ('pismo', models.CharField(max_length=16)),
                ('broj_strana', models.IntegerField()),
                ('broj_primeraka', models.IntegerField()),
                ('vrsta_poveza', models.CharField(max_length=16)),
            ],
        ),
    ]
