# Generated by Django 3.1.1 on 2020-09-28 03:51

import biblioteka.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_korisnik_rola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogadjaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=biblioteka.api.models.upload_path)),
                ('opis', models.CharField(max_length=64)),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Primerak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_broj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=biblioteka.api.models.upload_path)),
                ('opis', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Zaduzenje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_zaduzenja', models.DateField()),
                ('datum_vracanja', models.DateField()),
            ],
        ),
    ]
