# Generated by Django 3.1.1 on 2020-10-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_knjigaslika_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knjigaslika',
            name='filename',
        ),
    ]
