# Generated by Django 3.1.1 on 2020-10-01 17:25

import biblioteka.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_knjigaslika_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjigaslika',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=biblioteka.api.models.upload_path),
        ),
    ]
