# Generated by Django 3.1.1 on 2020-10-01 18:15

import biblioteka.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201001_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjigaslika',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=biblioteka.api.models.upload_path),
        ),
    ]
