# Generated by Django 3.1.1 on 2020-10-02 15:48

import biblioteka.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201002_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='knjiga',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=biblioteka.api.models.upload_path),
        ),
    ]
