# Generated by Django 3.1.1 on 2020-10-02 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_knjiga_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnjigaSlika',
        ),
    ]
