# Generated by Django 3.1.1 on 2020-10-03 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_knjigaslika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerak',
            name='id_knjige',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.knjiga'),
        ),
    ]
