# Generated by Django 3.1.1 on 2020-10-03 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201003_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaduzenje',
            name='id_clana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.knjiga'),
        ),
        migrations.AlterField(
            model_name='zaduzenje',
            name='inv_broj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.primerak'),
        ),
    ]
