# Generated by Django 3.1.1 on 2020-10-03 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201004_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezervacija',
            name='inv_broj',
        ),
        migrations.AddField(
            model_name='rezervacija',
            name='id_knjige',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='api.knjiga'),
            preserve_default=False,
        ),
    ]
