# Generated by Django 3.1.1 on 2020-10-03 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20201004_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezervacija',
            old_name='id_clana',
            new_name='username',
        ),
    ]
