# Generated by Django 3.1.1 on 2020-10-03 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20201004_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezervacija',
            old_name='username',
            new_name='id_clana',
        ),
    ]
