# Generated by Django 3.1.1 on 2020-10-04 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20201004_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervacija',
            name='datum_rezervacije',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
